version: '3.5'
services:
  bsms_database_service:
    container_name: bsms-database
    restart: unless-stopped
    image: mysql:8
    networks:
      - bsms-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gabinetkosmetycznydb
    volumes:
      - './gabinet-kosmetyczny-data/sql:/docker-entrypoint-initdb.d'
    ports:
      - "3306:3306"

  bsms_phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: bsms_database_service
      PMA_USER: root
      PMA_PASSWORD: password
    networks:
      - bsms-mysql
    ports:
      - "8080:80"

networks:
  bsms-mysql:
